// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'Event.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 1986100898823463147),
      name: 'EventEntry',
      lastPropertyId: const obx_int.IdUid(9, 1073779063438954990),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7486385045765780929),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5414971513986761040),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4844047259015545644),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 183966209052605801),
            name: 'pinned',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1754967819261549778),
            name: 'created',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4298174358140427620),
            name: 'entrytype',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 2749099483130914061),
            name: 'upcoming_start',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 1073779063438954990),
            name: 'upcoming_end',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 1986100898823463147),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [7887221647040631017],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    EventEntry: obx_int.EntityDefinition<EventEntry>(
        model: _entities[0],
        toOneRelations: (EventEntry object) => [],
        toManyRelations: (EventEntry object) => {},
        getId: (EventEntry object) => object.id,
        setId: (EventEntry object, int id) {
          object.id = id;
        },
        objectToFB: (EventEntry object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final descriptionOffset = fbb.writeString(object.description);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, descriptionOffset);
          fbb.addBool(3, object.pinned);
          fbb.addInt64(4, object.created.millisecondsSinceEpoch);
          fbb.addInt64(6, object.entrytype);
          fbb.addInt64(7, object.upcoming_start.millisecondsSinceEpoch);
          fbb.addInt64(8, object.upcoming_end.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final pinnedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);
          final createdParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0));
          final upcoming_startParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0));
          final upcoming_endParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0));
          final object = EventEntry(titleParam, descriptionParam, pinnedParam,
              createdParam, upcoming_startParam, upcoming_endParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..entrytype =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [EventEntry] entity fields to define ObjectBox queries.
class EventEntry_ {
  /// see [EventEntry.id]
  static final id =
      obx.QueryIntegerProperty<EventEntry>(_entities[0].properties[0]);

  /// see [EventEntry.title]
  static final title =
      obx.QueryStringProperty<EventEntry>(_entities[0].properties[1]);

  /// see [EventEntry.description]
  static final description =
      obx.QueryStringProperty<EventEntry>(_entities[0].properties[2]);

  /// see [EventEntry.pinned]
  static final pinned =
      obx.QueryBooleanProperty<EventEntry>(_entities[0].properties[3]);

  /// see [EventEntry.created]
  static final created =
      obx.QueryDateProperty<EventEntry>(_entities[0].properties[4]);

  /// see [EventEntry.entrytype]
  static final entrytype =
      obx.QueryIntegerProperty<EventEntry>(_entities[0].properties[5]);

  /// see [EventEntry.upcoming_start]
  static final upcoming_start =
      obx.QueryDateProperty<EventEntry>(_entities[0].properties[6]);

  /// see [EventEntry.upcoming_end]
  static final upcoming_end =
      obx.QueryDateProperty<EventEntry>(_entities[0].properties[7]);
}
